dictionaries = ["en_gb"]
words = [
    "antipattern",
    "antipatterns",
    "asynchrosity",
    "backupping",
    "colframe",
    "distributedness",
    "ifthenelse",
    "mak",
    "orchestrator",
    "orchestrators",
    "parallelisable",
    "parallelising",
    "patt",
    "shortpolling",
]
